// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTIcMtQCzrdtEHYNDaIhUQReVLEN7njw',
    appId: '1:353720531459:web:c70b870868b99c3a3fac36',
    messagingSenderId: '353720531459',
    projectId: 'tracker-flutter-7e294',
    authDomain: 'tracker-flutter-7e294.firebaseapp.com',
    storageBucket: 'tracker-flutter-7e294.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIntxSqj98QHxElVtnhB7MvbnD98Ux4jE',
    appId: '1:353720531459:android:afd835bba2d733233fac36',
    messagingSenderId: '353720531459',
    projectId: 'tracker-flutter-7e294',
    storageBucket: 'tracker-flutter-7e294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2jwLdVMwDCq5AACSsqmTjLuiBG68k2Uw',
    appId: '1:353720531459:ios:5343777b4490e2a73fac36',
    messagingSenderId: '353720531459',
    projectId: 'tracker-flutter-7e294',
    storageBucket: 'tracker-flutter-7e294.firebasestorage.app',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2jwLdVMwDCq5AACSsqmTjLuiBG68k2Uw',
    appId: '1:353720531459:ios:5343777b4490e2a73fac36',
    messagingSenderId: '353720531459',
    projectId: 'tracker-flutter-7e294',
    storageBucket: 'tracker-flutter-7e294.firebasestorage.app',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTIcMtQCzrdtEHYNDaIhUQReVLEN7njw',
    appId: '1:353720531459:web:61f5be6ee60553353fac36',
    messagingSenderId: '353720531459',
    projectId: 'tracker-flutter-7e294',
    authDomain: 'tracker-flutter-7e294.firebaseapp.com',
    storageBucket: 'tracker-flutter-7e294.firebasestorage.app',
  );
}
